export const ADD_GOOD_TO_CART = "ADD_GOOD_TO_CART"
export const DELETE_GOOD_FROM_CART = "DELETE_GOOD_FROM_CART"
export const CHANGE_QUANTITY = "CHANGE_QUANTITY"
export const EMPTY_CART = "EMPTY_CART"
