export const ADD_GOOD_TO_CART = "ADD_GOOD_TO_CART"
export const DELETE_GOOD_FROM_CART = "DELETE_GOOD_FROM_CART"
export const INCREASE_QUANTITY = "INCREASE_QUANTITY"
export const DECREASE_QUANTITY = "DECREASE_QUANTITY"
