export const GET_GOOD = "GET_GOOD"
export const GET_GOODS = "GET_GOODS"
export const ADD_GOOD = "ADD_GOOD"
export const DELETE_GOOD = "DELETE_GOOD"
export const FILTER_GOODS = "FILTER_GOODS"
export const FILTER_GOODS_SAGA = "FILTER_GOODS_SAGA"
export const SELLER_ADD_GOOD = "SELLER_ADD_GOOD"
